version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Upgrade pip in virtual environment
          command: venv/bin/pip install --upgrade pip
      - run:
          name: Install dependencies
          command: venv/bin/pip install -r requirements.txt
      - run:
          name: Run tests
          command: venv/bin/pytest

workflows:
  version: 2
  build:
    jobs:
      - build

