#config
version: 2.1
joba:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout

      - run:
config2

          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - run:
main
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests and collect coverage
          command: |
            coverage run -m unittest discover -s tests
            coverage xml
            coverage report -m

      - run:
          name: Upload Code Climate coverage report
          command: |
            ./cc-test-reporter after-build --input-type coverage.py --coverage-file coverage.xml
